### PR TITLE
Inherit `@Internal`

### PR DESCRIPTION
**Pull request by alexander-yevsyukov**
This PR makes `@Internal` annotation `@Inherited`.

### CODE REVIEW

**Comment by alexander-yevsyukov** [comment]
@dmdashenkov, PTAL.

**Comment by alexander-yevsyukov** [comment]
@dmdashenkov, PTAL.

**Comment by dmdashenkov** [comment]
@alexander-yevsyukov 
There is a counterexample. `io.spine.server.delivery.Delivery` is marked `@Internal`, but `io.spine.server.aggregate.AggregateDelivery` is marked as `@SPI`.

I believe, there _may_ be cases when an internal API is implemented in a public API class.

**Comment by alexander-yevsyukov** [comment]
Think of it as if `@Internal` makes a class invisible. We cannot make its descendant visible without making the parent class visible.

**Comment by dmdashenkov** [comment]
@alexander-yevsyukov 
Actually, we can. This way, Java allows making subtypes of a package-local class `public`.

**Comment by alexander-yevsyukov** [comment]
It's not the same thing. Making a class `public` is a deliberate action. Here we want to avoid exposing classes or methods that are already `public` to the end user API by mistake.

**Pull request merged**
